# ============================================================================
# QEARIS - Alternative Cloud Build Configuration (Docker-based)
# ============================================================================
#
# This Cloud Build configuration uses Dockerfile-based builds instead of
# buildpacks and avoids Git repository link requirements.
#
# USE THIS WHEN:
#   You encounter the error:
#   "invalid argument: git repository link name must be in the format of
#    'projects//locations//connections//gitRepositoryLinks/'"
#
# This error occurs when Cloud Build triggers try to use 2nd-gen Git repository
# connections that are not properly configured.
#
# USAGE:
#   # Submit build manually from repository root:
#   gcloud builds submit --config deployment/cloud_run/cloudbuild-docker.yaml \
#     --substitutions=_GEMINI_API_KEY="your-api-key"
#
#   # Or with region override:
#   gcloud builds submit --config deployment/cloud_run/cloudbuild-docker.yaml \
#     --substitutions=_GEMINI_API_KEY="your-api-key",_REGION="europe-west1"
#
# NOTE: This file is designed to be triggered manually, not via Cloud Build
# triggers connected to Git repositories.
#
# ============================================================================

# Substitution variables (override at build time)
substitutions:
  _SERVICE_NAME: gemini-api-service
  _REGION: europe-west1
  _MEMORY: 2Gi
  _CPU: '2'
  _MIN_INSTANCES: '1'
  _MAX_INSTANCES: '10'
  _TIMEOUT: '300'
  _GEMINI_API_KEY: ''

# Build steps
steps:
  # ============================================================================
  # Step 1: Build Docker Image
  # ============================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
      - '-f'
      - 'dockerfile'
      - '.'
    waitFor: ['-']  # Start immediately

  # ============================================================================
  # Step 2: Push Image with Build ID Tag
  # ============================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BUILD_ID'
    waitFor: ['build']

  # ============================================================================
  # Step 3: Push Image with Latest Tag
  # ============================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-latest'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
    waitFor: ['push']

  # ============================================================================
  # Step 4: Deploy to Cloud Run
  # ============================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BUILD_ID'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '${_MEMORY}'
      - '--cpu'
      - '${_CPU}'
      - '--min-instances'
      - '${_MIN_INSTANCES}'
      - '--max-instances'
      - '${_MAX_INSTANCES}'
      - '--timeout'
      - '${_TIMEOUT}'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'GEMINI_API_KEY=${_GEMINI_API_KEY},ENVIRONMENT=production,LOG_LEVEL=INFO,CLOUD_RUN_REGION=${_REGION}'
    waitFor: ['push-latest']

  # ============================================================================
  # Step 5: Verify Deployment
  # ============================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'verify'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "============================================"
        echo "Deployment Verification"
        echo "============================================"
        echo ""
        echo "Getting service URL..."
        SERVICE_URL=$(gcloud run services describe ${_SERVICE_NAME} \
          --region ${_REGION} \
          --format "value(status.url)")
        
        if [ -z "$SERVICE_URL" ]; then
          echo "ERROR: Could not retrieve service URL"
          exit 1
        fi
        
        echo "Service URL: $SERVICE_URL"
        echo ""
        echo "Running health check..."
        
        # Retry health check up to 5 times
        for i in {1..5}; do
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" "$SERVICE_URL/health" || echo "000")
          if [ "$HTTP_CODE" = "200" ]; then
            echo "✓ Health check passed (HTTP 200)"
            echo ""
            echo "Deployment successful!"
            echo "Service URL: $SERVICE_URL"
            exit 0
          fi
          echo "Health check attempt $i: HTTP $HTTP_CODE"
          sleep 10
        done
        
        echo ""
        echo "WARNING: Health check did not return 200 after 5 attempts"
        echo "The service may still be starting. Check logs:"
        echo "  gcloud run services logs read ${_SERVICE_NAME} --region ${_REGION}"
        exit 1
    waitFor: ['deploy']

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'

# Build options
options:
  # Use higher-performance machine for faster builds
  machineType: 'E2_HIGHCPU_8'
  
  # Enable logging to Cloud Logging
  logging: CLOUD_LOGGING_ONLY
  
  # Dynamic substitution for environment variables
  dynamicSubstitutions: true

# Build timeout (20 minutes)
timeout: '1200s'
